sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

# cache:
#   timeout: 1000
#   directories:
#   - $HOME/.stack
#   - $TRAVIS_BUILD_DIR/.stack-work

matrix:
  include:
  # Build on linux
  - compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  # Build on macOS in addition to Linux
  # (for now MacOS is unsupported: issue with static linking)
  - compiler: ": #stack default osx"
    os: osx

before_install:
# Download and unpack the stack executable
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
  if [ -n "$CACHE_S3_VERSION" ]; then
    travis_retry curl -f -L https://github.com/fpco/cache-s3/releases/download/$CACHE_S3_VERSION/cache-s3-$CACHE_S3_VERSION-$TRAVIS_OS_NAME-x86_64.tar.gz | tar xz -C ~/.local/bin 'cache-s3'
    if [ -x $(readlink -f "~/.local/bin/cache-s3") ]; then
      cache-s3 --prefix=$TRAVIS_REPO_SLUG \
               --git-branch="$TRAVIS_BRANCH" \
               --suffix="$TRAVIS_OS_NAME" \
               restore stack --base-branch=master
      cache-s3 --prefix=$TRAVIS_REPO_SLUG \
               --git-branch="$TRAVIS_BRANCH" \
               --suffix="$TRAVIS_OS_NAME" \
               restore stack work --base-branch=master
    fi
  fi

install:
- |
  set -ex
  stack --no-terminal setup --no-reinstall > /dev/null
  set +ex

script:
- |
  set -ex
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    TIMEOUT="timeout"
  else
    TIMEOUT="gtimeout"
  fi
    ("$TIMEOUT" 1800 stack install --no-terminal --test) || ([ $? = 124 ] && echo "Timed out after 30min so the build will have to be picked up next time")
  set +ex

after_success:
- | # Do not cache PRs
  if [ "$TRAVIS_PULL_REQUEST" = false ]; then
    travis_retry curl -L https://github.com/tfausak/github-release/releases/download/$GITHUB_RELEASE_VERSION/github-release-$TRAVIS_OS_NAME.gz | gunzip > github-release
    chmod a+x github-release
    stack exec -- cp $(which cache-s3) .
    tar -czf cache-s3.tar.gz cache-s3
    ./github-release upload --token=$GITHUB_TOKEN --repo=$TRAVIS_REPO_SLUG --file=cache-s3.tar.gz --tag=$TRAVIS_TAG --name=cache-s3-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86_64.tar.gz
  fi
